services:
  tests:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpunit"
    volumes:
      - ./:/project
  analysis:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpstan analyze ./src"
    volumes:
      - ./:/project
  standards:
    build: ./
    working_dir: /project
    command: bash -c "composer install && ./vendor/bin/phpcs"
    volumes:
      - ./:/project
